# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: smarthome.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'smarthome.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsmarthome.proto\x12\tsmarthome\"(\n\x13SensorStatusRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\t\"I\n\x14SensorStatusResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tis_active\x18\x02 \x01(\x08\x12\x12\n\nstatus_msg\x18\x03 \x01(\t\"\"\n\rStreamRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\t\"1\n\rReadingUpdate\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x32\xae\x01\n\x10SmartHomeService\x12R\n\x0fGetSensorStatus\x12\x1e.smarthome.SensorStatusRequest\x1a\x1f.smarthome.SensorStatusResponse\x12\x46\n\x0eStreamReadings\x12\x18.smarthome.StreamRequest\x1a\x18.smarthome.ReadingUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'smarthome_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORSTATUSREQUEST']._serialized_start=30
  _globals['_SENSORSTATUSREQUEST']._serialized_end=70
  _globals['_SENSORSTATUSRESPONSE']._serialized_start=72
  _globals['_SENSORSTATUSRESPONSE']._serialized_end=145
  _globals['_STREAMREQUEST']._serialized_start=147
  _globals['_STREAMREQUEST']._serialized_end=181
  _globals['_READINGUPDATE']._serialized_start=183
  _globals['_READINGUPDATE']._serialized_end=232
  _globals['_SMARTHOMESERVICE']._serialized_start=235
  _globals['_SMARTHOMESERVICE']._serialized_end=409
# @@protoc_insertion_point(module_scope)
