server {
    listen 80;

    location /api/readings {
        proxy_pass http://host.docker.internal:8080;
        proxy_set_header Host $host;
    }

    location /api/dashboard {
        proxy_pass http://host.docker.internal:8080; 
    }

    # Статус самого шлюза
    location /gw-status {
        return 200 "API Gateway is Active\n";
    }
}